version: "3.8"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc

  etherpad:
    image: etherpad/etherpad:stable
    container_name: etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt

  mail:
    image: bytemark/smtp
    container_name: mail
    restart: always
    ports:
      - "2525:25"

  back:
    image: back-doodle
    container_name: back-doodle
    hostname: back-doodle
    depends_on:
      - db
    build:
      context: .
      dockerfile: api/src/main/docker/Dockerfile.jvm
    restart: always
    environment:
      - doodle.internalPadUrl=http://etherpad:9001/
      - quarkus.datasource.jdbc.url=jdbc:mysql://db:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
  

  front:
    build: 
      context: ./front/
      dockerfile: Dockerfile
      target : prod
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./api/server-confs:/server-confs:ro
    environment:
      - SERVER_NAME=degas.diverse-team.fr
      - SERVE_FILES=yes
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - USE_LIMIT_REQ=no
      - PROXY_REAL_IP=yes
      - DISABLE_DEFAULT_SERVER=no